title: JiHan's Blog
subtitle: 随笔写写啦 (๑`･ᴗ･´๑)
description: 瘫着贼舒服
keywords: null
author: JiHan
language: zh-Hans
timezone: null
url: 'http://yoursite.com'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
plugins: hexo-generate-feed
theme: next
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  content: true
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  model:
    use: live2d-widget-model-koharu
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: false
deploy:
  type: git
  repository: 'https://github.com/JiHanHuang/JiHanHuang.github.io'
  branch: master
